source 'https://rubygems.org'

gem 'rake'
# Add your dependencies here:

gem "motion-cocoapods"
gem "afmotion" # Networking
gem "newclear" # Completely wipe out the simulator and rebuild
gem "ProMotion", "~> 2.5"
gem "ProMotion-XLForm" # Form screens

